# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad6690659f883e969676c8f14bfd86a5f7dbdcecc130ee4549422ec1965706ccd00438db4e6c51b899cdf40ab05bec96d5cbeb10eb259b9cb90fe6668175749e

test:
  secret_key_base: 016ab40612c864995ab7a2277d29de3b3c1e8e0637fcfdd9d57ac3ebd7a70d9ade41ac5e2c47c8a213d327b7c2dcfb1e80abebb120b26546b86b33f8c78aaaf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
